export {default as Associate } from "./Associate"
export {default as Blogs } from "./Blogs"
export {default as Landing } from "./Landing"
export {default as Mynavbar } from "./Mynavbar"
export {default as Offers } from "./Offers"
export {default as Services } from "./Services"
export {default as Success } from "./Success"
export {default as Footer } from "./Footer"